services:
  - type: web
    name: chichi-api
    runtime: python
    rootDir: chichi-api
    buildCommand: pip install -r requirements.txt
    startCommand: python seed.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: chihuahuasouthafrica@gmail.com
      - key: ADMIN_PASSWORD_HASH
        value: "$2b$12$tpr32b.w61jpWvgnNnui.uaysekoNrOgeEOw5YvQyy102JB25eRzm"
      - key: PAYFAST_MERCHANT_ID
        value: "35726985"
      - key: PAYFAST_MERCHANT_KEY
        value: "gp3je4kljmbsi"
      - key: PAYFAST_PASSPHRASE
        value: ""
      - key: FRONTEND_URL
        value: https://chihuahuasouthafrica.com
      - key: BACKEND_URL
        value: https://chichi-api-7k6y.onrender.com
