services:
  - type: web
    name: chichi-api
    runtime: python
    rootDir: chichi-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@chihuahuasa.co.za
      - key: ADMIN_PASSWORD_HASH
        value: "$2b$12$N3taTWoHGXCpzSy3hWvDouwQx0xF18ug974DXmXIQo6mwqYUE5voS"
